bot:
    dockerfile: Dockerfile
    build: .
    volumes:
        - ./:/app/
    command: bash -c "pip install -r requirements.txt && pm2 start bot.py --interpreter=python --no-daemon --watch"
    working_dir: /app
    environment:
        TELEGRAM_TOKEN: $TELEGRAM_TOKEN
